### ISSUE TITLE
IllegalArgumentException: Unexpected packet received during server login process!

### ISSUE THREAD

**Issue by mibby** [WaterfallMC/Waterfall#275]
Waterfall dev 218
Paper dev 1547

Noticed this error in Waterfall console when this specific person tried connecting.
```
[11:57:06] [Netty Worker IO Thread #15/INFO]: [/ip-censored:50574] <-> InitialHandler has connected
[11:57:07] [Netty Worker IO Thread #15/INFO]: [Charliethetrex|/ip-censored:50574] <-> ServerConnector [Server] has connected
[11:57:07] [Netty Worker IO Thread #15/INFO]: [/ip-censored:50574|Charliethetrex] -> UpstreamBridge has disconnected
[11:57:07] [Netty Worker IO Thread #15/INFO]: [/ip-censored:50574|Charliethetrex] <-> DownstreamBridge <-> [Server] has disconnected
[11:57:14] [Netty Worker IO Thread #3/INFO]: [/ip-censored:50579] <-> InitialHandler has connected
[11:57:14] [Netty Worker IO Thread #3/INFO]: [Charliethetrex|/ip-censored:50579] <-> ServerConnector [Server] has connected
[11:57:14] [Netty Worker IO Thread #3/INFO]: [/ip-censored:50579|Charliethetrex] -> UpstreamBridge has disconnected
[11:57:14] [Netty Worker IO Thread #3/WARN]: No client connected for pending server!
[11:57:14] [Netty Worker IO Thread #3/ERROR]: [Charliethetrex|/ip-censored:50579] <-> ServerConnector [Server] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
0d02
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:157) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[11:57:14] [Netty Worker IO Thread #3/INFO]: [Charliethetrex|/ip-censored:50579] <-> ServerConnector [Server] has disconnected
[11:57:35] [Netty Worker IO Thread #14/INFO]: [/ip-censored:50581] <-> InitialHandler has connected
[11:57:35] [Netty Worker IO Thread #14/INFO]: [Charliethetrex|/ip-censored:50581] <-> ServerConnector [Server] has connected

[12:06:07] [Netty Worker IO Thread #6/INFO]: [/ip-censored:50625] <-> InitialHandler has connected
[12:06:07] [Netty Worker IO Thread #6/INFO]: [Charliethetrex|/ip-censored:50625] <-> ServerConnector [Server] has connected
[12:06:07] [Netty Worker IO Thread #6/INFO]: [/ip-censored:50625|Charliethetrex] -> UpstreamBridge has disconnected
[12:06:07] [Netty Worker IO Thread #6/WARN]: No client connected for pending server!
[12:06:07] [Netty Worker IO Thread #6/ERROR]: [Charliethetrex|/ip-censored:50625] <-> ServerConnector [Server] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
0d02
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:157) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:2a424bb:218]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[12:06:07] [Netty Worker IO Thread #6/INFO]: [Charliethetrex|/ip-censored:50625] <-> ServerConnector [Server] has disconnected

```

**Comment by mibby** [comment]
Checking Paper console logs, it seems it also errored there. Perhaps it is instead a plugin issue?

```
[12:06:07] [LoginProcessingThread/INFO]: UUID of player Charliethetrex is 83e2f139-c8d2-401c-a2c7-14cf74c5f726
[12:06:07] [Server thread/INFO]: [VanishNoPacket] Charliethetrex disappeared.
[12:06:07] [pool-51-thread-1/WARN]: Exception in thread "pool-51-thread-1" java.lang.RuntimeException: java.util.NoSuchElementException: packet_handler
[12:06:07] [pool-51-thread-1/WARN]: 	at ru.nightexpress.divineitems.libs.packetlistener.channel.INCChannel$1.run(INCChannel.java:35)
[12:06:07] [pool-51-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:06:07] [pool-51-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:06:07] [pool-51-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:06:07] [pool-51-thread-1/WARN]: Caused by: java.util.NoSuchElementException: packet_handler
[12:06:07] [pool-51-thread-1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
[12:06:07] [pool-51-thread-1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260)
[12:06:07] [pool-51-thread-1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
[12:06:07] [pool-51-thread-1/WARN]: 	at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
[12:06:07] [pool-51-thread-1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:272)
[12:06:07] [pool-51-thread-1/WARN]: 	at ru.nightexpress.divineitems.libs.packetlistener.channel.INCChannel$1.run(INCChannel.java:33)
[12:06:07] [pool-51-thread-1/WARN]: 	... 3 more
```

```
[12:21:14] [LoginProcessingThread/INFO]: UUID of player Charliethetrex is 83e2f139-c8d2-401c-a2c7-14cf74c5f726
[12:21:14] [Netty Server IO #1/WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.12.2.jar:git-Paper-1547]
[12:21:14] [Server thread/INFO]: [VanishNoPacket] Charliethetrex disappeared.
[12:21:14] [pool-51-thread-2/WARN]: Exception in thread "pool-51-thread-2" java.lang.RuntimeException: java.util.NoSuchElementException: packet_handler
[12:21:14] [pool-51-thread-2/WARN]: 	at ru.nightexpress.divineitems.libs.packetlistener.channel.INCChannel$1.run(INCChannel.java:35)
[12:21:14] [pool-51-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:21:14] [pool-51-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:21:14] [pool-51-thread-2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:21:14] [pool-51-thread-2/WARN]: Caused by: java.util.NoSuchElementException: packet_handler
[12:21:14] [pool-51-thread-2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
[12:21:14] [pool-51-thread-2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260)
[12:21:14] [pool-51-thread-2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
[12:21:14] [pool-51-thread-2/WARN]: 	at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
[12:21:14] [pool-51-thread-2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:272)
[12:21:14] [pool-51-thread-2/WARN]: 	at ru.nightexpress.divineitems.libs.packetlistener.channel.INCChannel$1.run(INCChannel.java:33)
[12:21:14] [pool-51-thread-2/WARN]: 	... 3 more
[12:21:14] [Server thread/INFO]: Charliethetrex[/98.206.136.72:35570] logged in with entity id 1113770 at ([spawn]-136.5, 82.0, 0.5)
[12:21:14] [Craft Scheduler Thread - 419/INFO]: Async with thread: Craft Scheduler Thread - 419
[12:21:14] [Server thread/INFO]: Charliethetrex lost connection: Internal Exception: java.io.IOException: Connection reset by peer

```

**Comment by electronicboy** [comment]
Duplicate of #264 
Your server is sending invalid data to the proxy

**Comment by mibby** [comment]
Is there any way to find out what invalid data is being sent?

**Comment by Janmm14** [comment]
The hex content is in the error: 0d02

Edit: But its likely that the issue here is divineitems.

**Comment by mibby** [comment]
Thanks, I also came to that possible conclusion and forwarded it to the appropriate dev. I have removed the plugin for now and will see if any further crashing occurs without it.
