### ISSUE TITLE
I'm getting this error:

### ISSUE THREAD

**Issue by BarraR3port** [WaterfallMC/Waterfall#692]
[11:17:12 ERROR]: [/45.232.34.234:55492|BarraR3port] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.GameState in phase GAME with direction TO_CLIENT
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at me.neznamy.tab.platforms.bungee.BungeePipelineInjector$1.write(BungeePipelineInjector.java:78) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:315) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:198) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.GameState in phase GAME with direction TO_CLIENT
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:399) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:602) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[waterfall-1.17-449.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        ... 49 more
[11:17:12 INFO]: [BarraR3port] disconnected with: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.GameState in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125

**Comment by Janmm14** [comment]
Likely problem of the tab plugin you have on bungeecord

**Comment by Janmm14** [comment]
You have at least one plugin which does stuff bejond the supported plugin api.

**Comment by BarraR3port** [comment]
Now the second question, which plugin could be causing this error?
I'm also getting this one too: THe received string lenght is loger than allowed (19>16)

**Comment by electronicboy** [comment]
All we can tell you is that you have oversized strings somewhere, as from where? no idea, usernames are the biggest "16 chars" thing I can think of, but, otherwise, no idea

**Comment by Janmm14** [comment]
16 chars could also be the limit of 1.8 teams or tablist
