### ISSUE TITLE
Kicked with: server_went_down

### ISSUE THREAD

**Issue by andreasdc** [WaterfallMC/Waterfall#737]
I'm often getting kicked after connecting to the server with server_went_down message, but there are no errors on spigot or bungee.

**Comment by electronicboy** [comment]
You'd need to work out why the connection disappeared, there is nothing here to suggest that this is a waterfall issue, and this is not the place for support

**Comment by andreasdc** [comment]
> You'd need to work out why the connection disappeared, there is nothing here to suggest that this is a waterfall issue, and this is not the place for support

Kick reason is from proxy, so how to analyze it?

**Comment by electronicboy** [comment]
Kick reason is from the proxy because the server lost connection and thus, the proxy no longer having somewhere to connect you to, kicked you from the proxy

There is often logs when this stuff happens, but, not always, you'll have to try to deduce what caused it

**Comment by andreasdc** [comment]
> Kick reason is from the proxy because the server lost connection and thus, the proxy no longer having somewhere to connect you to, kicked you from the proxy
> 
> There is often logs when this stuff happens, but, not always, you'll have to try to deduce what caused it

I only have 'disconnected' as reason in the logs, no errors or anything.

**Comment by andreasdc** [comment]
> Kick reason is from the proxy because the server lost connection and thus, the proxy no longer having somewhere to connect you to, kicked you from the proxy
> 
> There is often logs when this stuff happens, but, not always, you'll have to try to deduce what caused it

I have the error:
java.lang.IllegalArgumentException: Objective sbUsername already exists in this scoreboard

**Comment by andreasdc** [comment]
Full error:
java.lang.IllegalArgumentException: Objective sbUsername already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:189) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:87) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:132) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8e37934:unknown]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by electronicboy** [comment]
#318

**Comment by andreasdc** [comment]
> #318

What's the fix?

**Comment by electronicboy** [comment]
There is no fix atm, don't have duplicate team names across servers, basically

**Comment by andreasdc** [comment]
> There is no fix atm, don't have duplicate team names across servers, basically

Isn't it creating memory leak for clients?

**Comment by andreasdc** [comment]
> There is no fix atm, don't have duplicate team names across servers, basically

Also shouldn't it just be overriden, as you can't do much with scoreboards from another server?

**Comment by electronicboy** [comment]
It's not creating a leak, there is generally a race condition within the logic due to how server switches occur which makes it much harder to solve than just "overriding", please read the linked issue

**Comment by andreasdc** [comment]
> It's not creating a leak, there is generally a race condition within the logic due to how server switches occur which makes it much harder to solve than just "overriding", please read the linked issue

1st server didn't have any scoreboards, should it happen in that way?

**Comment by andreasdc** [comment]
@electronicboy no way that this would happen again, something is more messed up than that.

**Comment by electronicboy** [comment]
This is not the place for a back and forth discussion, no need to spam peoples emails; You clearly have something using scoreboards, and the name doesn't look unique, so, likely some plugin on both is causing duplicate names across server instances

**Comment by andreasdc** [comment]
> This is not the place for a back and forth discussion, no need to spam peoples emails; You clearly have something using scoreboards, and the name doesn't look unique, so, likely some plugin on both is causing duplicate names across server instances

Shouldn't it clear scoreboard objectives when switching the server?

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Waterfall/issues/737#issuecomment-1109077313

**Comment by andreasdc** [comment]
> [#737 (comment)](https://github.com/PaperMC/Waterfall/issues/737#issuecomment-1109077313)

So If I create objective with name I can't use it anymore on any server during the same proxy connection?

**Comment by electronicboy** [comment]
Yes.

**Comment by andreasdc** [comment]
> Yes.

Well that's a litte bit problematic, right? 🚀 
I had the same names on every server and I didn't have this problem earlier.

**Comment by Janmm14** [comment]
> Yes.

Doesn't your "yes" mean that vanilla scoreboards will cause this problem once you enter the same server for the 2nd time in your proxy connection?

**Comment by electronicboy** [comment]
Yes, you can't have duplicate team names across servers without it breaking, this is a long standing bungeecord issue, hence the already opened issue for this; resolving this however is a PITA because aspects of this fall into the API, of which any fix for this is potentially going to introduce race conditions or inconsistencies with the API

**Comment by ColorsASD** [comment]
I had a similar problem on 1.19.1 and 1.19.2.
The connection with the server was continuously disconnected with the message "server went down".
Although I did not experience an error line.

[BungeePackFix](https://www.spigotmc.org/resources/%E2%9A%99%EF%B8%8Fbungeepackfix.96794/) update solved the problem, I hope I can help someone with this as well.

**Comment by Arobcher** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
