### ISSUE TITLE
Waterfall does not start anymore on the current build

### ISSUE THREAD

**Issue by KaiKikuchi** [WaterfallMC/Waterfall#742]
I just tested this commit https://github.com/PaperMC/Waterfall/commit/958ae29cab8832d1093f4fa9292b345cd12d9a4b

It builds, but the proxy server does not start.

These are the commands I used to clone and build Waterfall:
```
git clone https://github.com/PaperMC/Waterfall/
cd Waterfall
./waterfall b
```

It builds fine. I copied the Waterfall-Proxy/bootstrap/target/Waterfall.jar in a new folder, then running it gives the following error:
```
> java -jar Waterfall.jar
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name messages, locale en
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
        at net.md_5.bungee.BungeeCord.<init>(BungeeCord.java:198)
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:64)
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

```

This is the entire output that the command gives.

I can build and run the previous commit just fine.

**Comment by NoahvdAa** [comment]
Thanks, working on a fix!
