### ISSUE TITLE
Error on attempt to connect to server behind the waterfall

### ISSUE THREAD

**Issue by radiant-ai** [WaterfallMC/Waterfall#749]
Error on waterfall `build 493`. Happens on both 1.18.2 and 1.19 clients. Presumably this happens as soon as one of the Waterfall plugins send a message to player. Did not happen on pre-1.19 builds.
```
-> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.SystemChat in phase GAME with direction TO_CLIENT
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:515) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:543) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:484) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:457) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection$4.operationComplete(UserConnection.java:381) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.UserConnection$4.operationComplete(UserConnection.java:356) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:674) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```

**Comment by radiant-ai** [comment]
I have a bit more context. This error happens when one of my Bungee plugins tries to connect a player to 1.19 experimental server. Interesting part is that this server can be turned off completely, but this error will still appear. So it is something on the Waterfall side.

**Comment by c0wg0d** [comment]
Having the same issue in build 494.

**Comment by aXe18** [comment]
Me too having same issue whit this build.

**Comment by Vooperino** [comment]
Same issue as well

**Comment by radiant-ai** [comment]
As of build 495 the issue persists but now no error is printed neither in client nor in console

**Comment by radiant-ai** [comment]
The issue is most likely on ViaVersion side as removing it from proxy and installing it on server resolves the issue

**Comment by radiant-ai** [comment]
Closing as it was an issue of ViaVersion

**Comment by xism4** [comment]
> The issue is most likely on ViaVersion side as removing it from proxy and installing it on server resolves the issue

This is not a Waterfall issue, don't use viaversion on your proxy, is not recommended.
