### ISSUE TITLE
The proxy server does not want to turn on

### ISSUE THREAD

**Issue by EPGMooky** [WaterfallMC/Waterfall#754]
Hi, i cant start my waterfall server.
I use latest build 496
No plugins, clear server
Every time I try to start the server without config.yml server will start but after the next start/restart the server no longer works.
This error appear:
[14:20:54 ERROR]: Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
[14:20:54 ERROR]:       at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:275)
[14:20:54 ERROR]:       at net.md_5.bungee.conf.Configuration.load(Configuration.java:96)
[14:20:54 ERROR]:       at io.github.waterfallmc.waterfall.conf.WaterfallConfiguration.load(WaterfallConfiguration.java:67)
[14:20:54 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
[14:20:54 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[14:20:54 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15
![unknown](https://user-images.githubusercontent.com/42835070/173605711-4dd34c07-0e8d-4611-a201-8c589d404ea0.png)
![unknown2](https://user-images.githubusercontent.com/42835070/173606341-7e6c3407-f835-41c6-b4a9-d0137403ef12.png)
)

**Comment by NoahvdAa** [comment]
Your query port shouldn't be a string (remove the ').

**Comment by EPGMooky** [comment]
Thanks a lot!! This is hosting default config

**Comment by Janmm14** [comment]
> Thanks a lot!! This is hosting default config

Then you should change hosting.

**Comment by electronicboy** [comment]
query port should be a number, not a string, the quotes need removing
