### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by proektgames** [WaterfallMC/Waterfall#755]
`[19:08:34 ERROR]: [/***.***.***.***:52433|qkback] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot read the array length because "properties" is null
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at net.md_5.bungee.connection.InitialHandler$1.sendPacket(InitialHandler.java:100) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:573) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because "properties" is null
        at net.md_5.bungee.protocol.DefinedPacket.writeProperties(DefinedPacket.java:243) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at net.md_5.bungee.protocol.packet.LoginSuccess.write(LoginSuccess.java:55) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[waterfall-1.19-491.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:eceb6b9:491]
        ... 16 more`
A person cannot enter with such an error. How to fix it?

**Comment by electronicboy** [comment]
update.
