### ISSUE TITLE
Bungee kick error

### ISSUE THREAD

**Issue by NoltoxGit** [WaterfallMC/Waterfall#816]
Hello !

I have this error when a player try to join a subserver with **1.20.2** version.

```log
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftDecoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at net.md_5.bungee.netty.ChannelWrapper.getDecodeProtocol(ChannelWrapper.java:41) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:352) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at net.md_5.bungee.protocol.packet.StartConfiguration.handle(StartConfiguration.java:35) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9cb6909:538]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13:00:52] [Netty Worker IO Thread #7/INFO]: [lysou33] disconnected with: NullPointerException : Cannot invoke "net.md_5.bungee.protocol.MinecraftDecoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null @ net.md_5.bungee.netty.ChannelWrapper:41
```

**Comment by Janmm14** [comment]
is being discussed on bungeecords issue tracker atm
