### ISSUE TITLE
A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5c56a117

### ISSUE THREAD

**Issue by MrAnrehah** [WaterfallMC/Waterfall#824]
Occurs when connecting, while the player is shown NULL
```
[14:56:06 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5c56a117
java.lang.IllegalStateException: Cancelled ServerConnectEvent with no server or disconnect.
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:340) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:321) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:298) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:291) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.connection.InitialHandler.finish2(InitialHandler.java:666) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.connection.InitialHandler.access$1300(InitialHandler.java:76) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:636) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.Thread.run(Thread.java:1589) [?:?]

```

**Comment by xism4** [comment]
> Occurs when connecting, while the player is shown NULL
> 
> ```
> [14:56:06 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5c56a117
> java.lang.IllegalStateException: Cancelled ServerConnectEvent with no server or disconnect.
>         at net.md_5.bungee.UserConnection.connect(UserConnection.java:340) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at net.md_5.bungee.UserConnection.connect(UserConnection.java:321) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at net.md_5.bungee.UserConnection.connect(UserConnection.java:298) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at net.md_5.bungee.UserConnection.connect(UserConnection.java:291) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at net.md_5.bungee.connection.InitialHandler.finish2(InitialHandler.java:666) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at net.md_5.bungee.connection.InitialHandler.access$1300(InitialHandler.java:76) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:636) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
>         at java.lang.Thread.run(Thread.java:1589) [?:?]
> ```

All i can see is that something cancelled the server connection event

Try without plugins on a vanilla enviorment

**Comment by MrAnrehah** [comment]
> > Occurs when connecting, while the player is shown NULL
> > ```
> > [14:56:06 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5c56a117
> > java.lang.IllegalStateException: Cancelled ServerConnectEvent with no server or disconnect.
> >         at net.md_5.bungee.UserConnection.connect(UserConnection.java:340) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at net.md_5.bungee.UserConnection.connect(UserConnection.java:321) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at net.md_5.bungee.UserConnection.connect(UserConnection.java:298) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at net.md_5.bungee.UserConnection.connect(UserConnection.java:291) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at net.md_5.bungee.connection.InitialHandler.finish2(InitialHandler.java:666) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at net.md_5.bungee.connection.InitialHandler.access$1300(InitialHandler.java:76) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:636) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
> >         at java.lang.Thread.run(Thread.java:1589) [?:?]
> > ```
> 
> All i can see is that something cancelled the server connection event
> 
> Try without plugins on a vanilla enviorment

Yes, indeed, the error occurred due to the mcAuth plugin.
https://github.com/bivashy/MC-Auth-with-Link/issues/102

**Comment by electronicboy** [comment]
Not a waterfall issue, a plugin induced what to the proxy is an illegal state (i.e. we can't allow a player to sit around with no connection to a server)
